-- CreateEnum
CREATE TYPE "TipoFlashcard" AS ENUM ('DEFINICAO', 'EXPLICACAO', 'EXEMPLO', 'APLICACAO', 'CONTRASTE', 'COMPLETAR', 'ORDENACAO', 'VERDADEIRO_FALSO', 'MULTIPLA_ESCOLHA', 'RELACIONAL', 'ERRO_COMUM');

-- AlterTable
ALTER TABLE "flashcards" ADD COLUMN "tipo" "TipoFlashcard";
